# plugin id, các khác nhau gi?a các plugin
plugin.id=ptdt

# version
plugin.version=1.0.0

# ???ng d?n file java config v?a t?o ? trên
plugin.class=com.fds.flexdata.plugin.ptdt.configuration.PhatTrienDoThiPlugin